name = "PedigreeBase"
uuid = "9e3bf72a-84c4-4798-98fd-c28eed5cded1"
authors = ["Yutaka Masuda <yutaka@uga.edu>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatrixDicts = "5cb6c4b0-9b79-11e8-24c9-f9621d252589"

[compat]
OffsetArrays = "^1"
SparseMatrixDicts = "^0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
